---
title: C26111
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C26111
helpviewer_keywords:
- C26111
ms.assetid: 85fc740a-3bbb-41b8-a848-95e243a08da9
ms.openlocfilehash: 193c94442230b1afa5a45c5314fd6ead4f3a62e1
ms.sourcegitcommit: 7bea0420d0e476287641edeb33a9d5689a98cb98
ms.translationtype: MT
ms.contentlocale: pt-BR
ms.lasthandoff: 02/17/2020
ms.locfileid: "77417349"
---
# <a name="c26111"></a>C26111

> aviso C26111: o chamador falha ao liberar bloqueio \<bloquear > antes de chamar a função \<Func >.

A anotação `_Requires_lock_not_held_` impõe uma pré-condição de que a contagem de bloqueios para o bloqueio especificado não pode ser maior que zero quando a função é chamada. Aviso C26111 é emitido quando uma função não libera o bloqueio antes de chamar outra função.

## <a name="example"></a>Exemplo

O exemplo a seguir gera C26111 de aviso porque a pré-condição de `_Requires_lock_not_held_` é violada pela chamada para `DoNotLock` na seção bloqueada.

```cpp
typedef struct _DATA
{
    CRITICAL_SECTION cs;
    int d;
} DATA;

_Requires_lock_not_held_(p->cs)

void DoNotLock(DATA* p)
{
    EnterCriticalSection(&p->cs);
    p->d = 0;
    LeaveCriticalSection(&p->cs);
}

void LockedFunction(DATA* p)
{
    EnterCriticalSection(&p->cs);
    DoNotLock(p); // Warning C26111
    LeaveCriticalSection(&p->cs);
}
```
