---
title: C28125
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C28125
helpviewer_keywords:
- C28125
ms.assetid: 3f7b8db4-6a64-4480-919e-3f3ceca7f948
ms.openlocfilehash: 3fa859f7bcc80040b62b538d37fb53d6169ff904
ms.sourcegitcommit: 7bea0420d0e476287641edeb33a9d5689a98cb98
ms.translationtype: MT
ms.contentlocale: pt-BR
ms.lasthandoff: 02/17/2020
ms.locfileid: "77417713"
---
# <a name="c28125"></a>C28125

> aviso C28125: a função deve ser chamada de dentro de um bloco try/Except

O driver está chamando uma função que deve ser chamada de dentro de um bloco try/Except, como [ProbeForRead](/windows-hardware/drivers/ddi/content/wdm/nf-wdm-probeforread), [ProbeForWrite](/windows-hardware/drivers/ddi/content/wdm/nf-wdm-probeforwrite), [MmProbeAndLockPages](/windows-hardware/drivers/ddi/content/wdm/nf-wdm-mmprobeandlockpages).

## <a name="example"></a>{1&gt;Exemplo&lt;1}

O exemplo de código a seguir gera este aviso:

```cpp
ProbeForRead(addr, len, 4);
```

O exemplo de código a seguir evita esse aviso:

```cpp
__try
{
    ProbeForRead(addr, len, 4);
}
__except(EXCEPTION_EXECUTE_HANDLER)
{
    Status = GetExceptionCode();
    ... report error status
}
```
