---
title: C6318
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6318
helpviewer_keywords:
- C6318
ms.assetid: 3284a83e-bb8e-461c-adcc-cfc66ceea05e
ms.openlocfilehash: ed49e96624ae332d59005c9e7ee117d19d8ab752
ms.sourcegitcommit: 7bea0420d0e476287641edeb33a9d5689a98cb98
ms.translationtype: MT
ms.contentlocale: pt-BR
ms.lasthandoff: 02/17/2020
ms.locfileid: "77419715"
---
# <a name="c6318"></a>C6318

> Aviso C6318: __try/\__except mal definidos: uso da constante EXCEPTION_CONTINUE_SEARCH ou outra constante que é avaliada como zero na expressão de filtro de exceção. O código no bloco do manipulador de exceção não foi executado

Esse aviso indica que, se ocorrer uma exceção no bloco protegido desse manipulador de exceções estruturado, a exceção não será tratada porque a constante `EXCECPTION_CONTINUE_SEARCH` é usada na expressão de filtro de exceção.

Esse código é equivalente ao bloco protegido sem o bloco manipulador de exceção porque o bloco Handler não é executado.

## <a name="example"></a>{1&gt;Exemplo&lt;1}

O código a seguir gera este aviso:

```cpp
#include <excpt.h>
#include <stdio.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except (EXCEPTION_CONTINUE_SEARCH) // warning C6318
  {
    puts("Exception Occurred");
  }
}
```

Para corrigir esse aviso, use o seguinte código:

```cpp
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except( (GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION) ?
                EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH )
  {
    puts("Access violation");
  }
}
```

## <a name="see-also"></a>Consulte também

[Instrução try-except](/cpp/cpp/try-except-statement)
