---
title: C6318
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6318
helpviewer_keywords:
- C6318
ms.assetid: 3284a83e-bb8e-461c-adcc-cfc66ceea05e
ms.openlocfilehash: 2da61e999542703d9846d7bb581f1691ec80d0f5
ms.sourcegitcommit: a1676bf6caae05ecd698f26ed80c08828722b237
ms.translationtype: MT
ms.contentlocale: pt-BR
ms.lasthandoff: 09/29/2020
ms.locfileid: "91509185"
---
# <a name="c6318"></a>C6318

> Aviso C6318: __try/_except mal definidos \_ : uso da constante EXCEPTION_CONTINUE_SEARCH ou outra constante que é avaliada como zero na expressão de filtro de exceção. O código no bloco do manipulador de exceção não foi executado

Esse aviso indica que, se ocorrer uma exceção no bloco protegido desse manipulador de exceções estruturado, a exceção não será tratada porque a constante `EXCECPTION_CONTINUE_SEARCH` é usada na expressão de filtro de exceção.

Esse código é equivalente ao bloco protegido sem o bloco manipulador de exceção porque o bloco Handler não é executado.

## <a name="example"></a>Exemplo

O código a seguir gera este aviso:

```cpp
#include <excpt.h>
#include <stdio.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except (EXCEPTION_CONTINUE_SEARCH) // warning C6318
  {
    puts("Exception Occurred");
  }
}
```

Para corrigir esse aviso, use o seguinte código:

```cpp
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except( (GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION) ?
                EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH )
  {
    puts("Access violation");
  }
}
```

## <a name="see-also"></a>Consulte também

[Instrução try-Except](../cpp/try-except-statement.md)
